//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class traduction {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal traduction() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Final.Properties.traduction", typeof(traduction).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annuler.
        /// </summary>
        public static string Annuler {
            get {
                return ResourceManager.GetString("Annuler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meteo.
        /// </summary>
        public static string App_Titre {
            get {
                return ResourceManager.GetString("App_Titre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changer la langue demande un redémarrage de l&apos;application..
        /// </summary>
        public static string Changement_Langue {
            get {
                return ResourceManager.GetString("Changement_Langue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jeton.
        /// </summary>
        public static string Jeton {
            get {
                return ResourceManager.GetString("Jeton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Langue.
        /// </summary>
        public static string Langue {
            get {
                return ResourceManager.GetString("Langue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude.
        /// </summary>
        public static string Latitude {
            get {
                return ResourceManager.GetString("Latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude.
        /// </summary>
        public static string Longitude {
            get {
                return ResourceManager.GetString("Longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        public static string Menu_Configuration {
            get {
                return ResourceManager.GetString("Menu_Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supprimer la région « {0} » ?.
        /// </summary>
        public static string Msg_Confirm_SupprimerRegion {
            get {
                return ResourceManager.GetString("Msg_Confirm_SupprimerRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude/Longitude invalides (ex: 46.57, -72.73)..
        /// </summary>
        public static string Msg_LatLon_Invalide {
            get {
                return ResourceManager.GetString("Msg_LatLon_Invalide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude entre -90 et 90, Longitude entre -180 et 180..
        /// </summary>
        public static string Msg_LatLon_Limites {
            get {
                return ResourceManager.GetString("Msg_LatLon_Limites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom de region invalide..
        /// </summary>
        public static string Msg_Nom_Region_Invalide {
            get {
                return ResourceManager.GetString("Msg_Nom_Region_Invalide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Région ajoutée!.
        /// </summary>
        public static string Msg_Region_Ajoutee {
            get {
                return ResourceManager.GetString("Msg_Region_Ajoutee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible de supprimer la région par défaut..
        /// </summary>
        public static string Msg_Region_Defaut_ImpossibleSupprimer {
            get {
                return ResourceManager.GetString("Msg_Region_Defaut_ImpossibleSupprimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une région avec ce nom existe déjà..
        /// </summary>
        public static string Msg_Region_Existe {
            get {
                return ResourceManager.GetString("Msg_Region_Existe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Région supprimée..
        /// </summary>
        public static string Msg_Region_Supprimee {
            get {
                return ResourceManager.GetString("Msg_Region_Supprimee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action refusée.
        /// </summary>
        public static string Msg_Titre_Action_Refusee {
            get {
                return ResourceManager.GetString("Msg_Titre_Action_Refusee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur.
        /// </summary>
        public static string Msg_Titre_Erreur {
            get {
                return ResourceManager.GetString("Msg_Titre_Erreur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur BD.
        /// </summary>
        public static string Msg_Titre_Erreur_BD {
            get {
                return ResourceManager.GetString("Msg_Titre_Erreur_BD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string Msg_Titre_Info {
            get {
                return ResourceManager.GetString("Msg_Titre_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom déjà utilisé.
        /// </summary>
        public static string Msg_Titre_Nom_DejaUtilise {
            get {
                return ResourceManager.GetString("Msg_Titre_Nom_DejaUtilise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valeurs hors limite.
        /// </summary>
        public static string Msg_Titre_Valeurs_HorsLimite {
            get {
                return ResourceManager.GetString("Msg_Titre_Valeurs_HorsLimite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valeurs invalides.
        /// </summary>
        public static string Msg_Titre_Valeurs_Invalides {
            get {
                return ResourceManager.GetString("Msg_Titre_Valeurs_Invalides", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jeton invalide ou expiré. Veuillez reconfigurer le jeton..
        /// </summary>
        public static string Msg_Token_Invalide {
            get {
                return ResourceManager.GetString("Msg_Token_Invalide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Région.
        /// </summary>
        public static string Region {
            get {
                return ResourceManager.GetString("Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sauvegarder.
        /// </summary>
        public static string Sauvegarder {
            get {
                return ResourceManager.GetString("Sauvegarder", resourceCulture);
            }
        }
    }
}
